### ISSUE TITLE
Plural for URI

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC#13]
One suggestion: Using the plural forms for the URIs:

```
/jobs
/jobs/{id}
/jobs/{jobId}/assets
/jobs/{jobId}/assets/{assetId}
etc.
```

It feels more intuitive (`GET /jobs` lists all the jobs, `GET /jobs/123` gets the job 123 among all jobs)

**Comment by Alino** [comment]
Thanks for your suggestion, I am not really sure about this, but I prefer singular because

**Convenience** Things can have irregular plural names. Sometimes they don't have one. But Singular names are always there

/order/12/orderdetail/4 is more readable and logical than /orders/12/orderdetails/4

**Database Table** A resource represents an entity like a database table. It should have a logical singular name. Here's the answer over table names.

**Class Mapping Classes are always singular**. ORM tools generate tables with same names as class names. As more and more tools are being used, singular names are becoming a standard.

source: https://metamug.com/article/rest-api-developers-dilemma.php

**Comment by Alino** [comment]
but on the other hand, many APIs are using plural. Even github, and facebook... So maybe more people are used to plural API design.

**Comment by Alino** [comment]
Kamino closed and cloned this issue to GALAglobal/TAPICC-API-implementation
