### ISSUE TITLE
XLIFF extraction and merging open source tool

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC#19]
Are you aware of such tools? Which one do you think is the best?
If we want to enable the TAPICC API to do merging and extracting, I suggest that we should use external tool for this. My vision is that it should be a command line tool which could be run in linux terminal.
Something like [tikal](https://okapiframework.org/wiki/index.php?title=How_to_Extract_Text_for_Translation)

few related questions
1. What file types do we want to support?
2. What would be the workflow/steps when a user is supposed to perform an extract or merge?
3. Should this be a separate API endpoint, or should this happen in the background when a user uploads a file (Asset) to a Task?
4. What happens after the extraction is done? Are we saving the XLIFF or adding data to database?
5. What happens after the merge is done? Are we somehow manipulating the database or producing a file?

**Comment by rmraya** [comment]
Generation of XLIFF files should not be part of TAPICC API. Implementers of the API should manage the creation of XLIFF files according to their own needs.

**Comment by ysavourel** [comment]
I agree with Rodolfo.
Or I'm not understanding something in the initial comment.

**Comment by stiofanmacthomais** [comment]
In terms of having a reference platform, I see no issue with providing a simple endpoint using Okapi or something.  I know from my perspective that we'll be using our own extraction/merge technology.

**Comment by rmraya** [comment]
There is no way you can add an end point with a set of generic parameters that covers all existing XLIFF generators.

**Comment by stiofanmacthomais** [comment]
I never said "generic" parameters, but I wasn't clear either :)  I don't mean to indicate that someone should provide a file processing endpoint as part of TAPICC. How one gets the XLIFF is less relevant than TAPICC requiring it, and "file processing" shouldn't really be in TAPICCs remit in my opinion.  Okapi tools can be used for this (or longhorn, or whichever.)

It would simply be a "nice-to-have" to be able to orchestrate an end to end roundtrip TAPICC-style over APIs instead of manually processing files for pre- and post-processing.

**Comment by Alino** [comment]
Kamino closed and cloned this issue to GALAglobal/TAPICC-API-implementation
